РК №1
java-park-mail-ru/fantasy-09-2016 pull request #1
Opened 2016-10-05 14:52 UTC by Alsaril

2016-10-05 22:41 UTC, KSolovyev requested changes

2016-10-05 22:41 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +            return ResponseEntity.badRequest().body(new FailedResponse("user already exists"));
Нужно отвыкать от голой передачи текста. Если вы вдруг решите сделать ваше приложение еще и на английском, то придется все переписывать. Я бы советовал перейти на код ошибки и(или) ключ локализованного сообщения. По ключу в клиенте достают текст сообщения на соответствующем языке

2016-10-05 22:41 UTC, KSolovyev commented
Аккуратно получилось, молодцы

2016-10-06 06:01 UTC, Alsaril commented
Изменил возвращаемое значение на код ошибки вместо самого сообщения.

2016-10-06 11:19 UTC, KSolovyev requested changes

2016-10-06 11:19 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +        EMPTY_FIELDS_IN_REQUEST,
В таких случаях лучше не привязываться к положению поля в enum. Надо сделать вот так:

```
private enum FailedResponseCode {
        EMPTY_FIELDS_IN_REQUEST(1),
        AUTH_REQUIRED(2),
        AUTH_FAILED(3),
        USER_ALREADY_EXITS(4),
        USER_NOT_EXIST(5),
        ALREADY_AUTHORIZED(6);

        private final int code;

        private FailedResponseCode(int code) {
            this.code = code;
        }
    }
```

использовать надо как `USER_NOT_EXIST.code`

2016-10-06 11:41 UTC, KSolovyev approved these changes

2016-10-06 11:41 UTC, merged